import type { DashboardSnapshot } from '@/lib/dashboard/types';

export const dashboardSnapshot = {
  meta: {
    dataSource: 'sample',
    label: 'Sample-Daten',
    description: 'Lokaler Beispiel-Snapshot, keine echten Projekt-Daten.',
  },
  projects: [
    {
      id: 'project_bubblesverse',
      name: 'Bubblesverse',
      key: 'BV',
      description: 'Monorepo-Arbeit, lokale Apps und Agent-Orchestrierung.',
      isArchived: false,
      health: 'aufmerksam',
      openIssues: 12,
      readyIssues: 4,
      blockedIssues: 2,
      memberCount: 3,
      agentTokenCount: 2,
    },
    {
      id: 'project_novari',
      name: 'Novari',
      key: 'NO',
      description: 'Kurs- und Kundenworkflows mit menschlicher Freigabe.',
      isArchived: false,
      health: 'stabil',
      openIssues: 7,
      readyIssues: 2,
      blockedIssues: 0,
      memberCount: 2,
      agentTokenCount: 1,
    },
    {
      id: 'project_yoink',
      name: 'Yoink',
      key: 'YK',
      description: 'Browser-Flows und lokale Automationsgrenzen.',
      isArchived: false,
      health: 'blockiert',
      openIssues: 5,
      readyIssues: 1,
      blockedIssues: 1,
      memberCount: 1,
      agentTokenCount: 0,
    },
  ],
  issues: [
    {
      id: 'BV-14',
      title: 'Agent-Zugriff mit projektbezogenen Tokens',
      projectKey: 'BV',
      status: 'bereit',
      priority: 'hoch',
      owner: 'Lio',
      planSteps: 5,
      approvalRequired: true,
    },
    {
      id: 'BV-12',
      title: 'Issue-Plan als strukturierte Arbeitsnotiz speichern',
      projectKey: 'BV',
      status: 'geplant',
      priority: 'hoch',
      owner: 'mrbubbles',
      planSteps: 3,
      approvalRequired: true,
    },
    {
      id: 'NO-08',
      title: 'Novari-Projekte für externe Mitarbeit freigeben',
      projectKey: 'NO',
      status: 'review',
      priority: 'mittel',
      owner: 'Martin',
      planSteps: 4,
      approvalRequired: true,
    },
    {
      id: 'YK-03',
      title: 'Lokale Browser-Flows für FavRelay absichern',
      projectKey: 'YK',
      status: 'blockiert',
      priority: 'mittel',
      owner: 'mrbubbles',
      planSteps: 2,
      approvalRequired: false,
    },
  ],
  agentTokens: [
    {
      id: 'token_codex_bv',
      label: 'codex-local-lio',
      projectKey: 'BV',
      scopes: ['issues:read', 'issues:write', 'runs:create'],
      state: 'aktiv',
      lastUsedAt: 'vor 12 Min.',
      expiresAt: 'läuft nicht automatisch ab',
    },
    {
      id: 'token_claude_no',
      label: 'claude-code-martin',
      projectKey: 'NO',
      scopes: ['issues:read', 'plans:write'],
      state: 'aktiv',
      lastUsedAt: 'vor 1 Std.',
      expiresAt: '2026-12-31T23:00:00.000Z',
    },
    {
      id: 'token_archive_bv',
      label: 'codex-archiv',
      projectKey: 'BV',
      scopes: ['issues:read'],
      state: 'pausiert',
      lastUsedAt: 'gestern',
      expiresAt: 'läuft nicht automatisch ab',
    },
  ],
  agentRuns: [
    {
      id: 'run_bv_14',
      issueId: 'BV-14',
      agentLabel: 'codex-local-lio',
      state: 'wartet',
      requestedBy: 'mrbubbles',
      lastEvent: 'Plan wartet auf Freigabe',
    },
    {
      id: 'run_no_08',
      issueId: 'NO-08',
      agentLabel: 'claude-code-martin',
      state: 'review',
      requestedBy: 'Martin',
      lastEvent: 'Diff bereit zur menschlichen Prüfung',
    },
  ],
  activity: [
    {
      id: 'event_plan_bv12',
      label: 'Plan für BV-12 aktualisiert',
      actor: 'Lio',
      occurredAt: '09:42',
      projectKey: 'BV',
      issueId: 'BV-12',
    },
    {
      id: 'event_scope_bv14',
      label: 'Token-Scope issues:write für BV vorbereitet',
      actor: 'mrbubbles',
      occurredAt: '09:28',
      projectKey: 'BV',
      issueId: 'BV-14',
    },
    {
      id: 'event_review_no08',
      label: 'Novari-Run in Review verschoben',
      actor: 'Martin',
      occurredAt: '08:55',
      projectKey: 'NO',
      issueId: 'NO-08',
    },
  ],
} satisfies DashboardSnapshot;
